version: '2'

services:
  nginx:
    container_name: docker_alpine_template_nginx
    image: nginx:latest
    ports:
      - 80
    depends_on:
      - app
    volumes:
      - ./docker-files/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./:/data/project
  app:
    container_name: docker_alpine_template_app
    build: .
    environment:
      APPLICATION_ENV: development
    depends_on:
      - mysql
    volumes:
      - ./docker-files/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./docker-files/php-development.ini:/etc/php7/conf.d/php-development.ini
      - ./:/data/project
  mysql:
    container_name: docker_alpine_template_mysql
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"