app:
  build: .
  ports:
    - 80
  environment:
    APPLICATION_ENV: development
  links:
    - mysql
  volumes:
    - ./docker-files/nginx.conf:/etc/nginx/nginx.conf
    - ./docker-files/www.conf:/etc/php-fpm/conf.d/www.conf
    - ./docker-files/php-development.ini:/etc/php/conf.d/php-development.ini
    - ./:/data/project

mysql:
  image: mysql
  ports:
    - 3306
  environment:
    MYSQL_DATABASE: "sample"
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
